param(
    [Parameter(Mandatory = $true)]
    [string]$DumpPath,

    [Parameter(Mandatory = $false)]
    [string]$OutputPath = (Join-Path (Get-Location) "legacy-public-restore.sql")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$allowedTables = @(
    'public."Games"',
    'public."QuestionsAnswers"',
    'public."Users"'
)

$tableDrops = @(
    'DROP TABLE IF EXISTS public."QuestionsAnswers" CASCADE;',
    'DROP TABLE IF EXISTS public."Games" CASCADE;',
    'DROP TABLE IF EXISTS public."Users" CASCADE;'
)

function New-Reader {
    param([string]$Path)

    $fileStream = [System.IO.File]::OpenRead($Path)
    if ($Path.EndsWith(".gz", [System.StringComparison]::OrdinalIgnoreCase)) {
        $gzipStream = New-Object System.IO.Compression.GzipStream(
            $fileStream,
            [System.IO.Compression.CompressionMode]::Decompress
        )
        $streamReader = New-Object System.IO.StreamReader($gzipStream)
        return [pscustomobject]@{
            Reader = $streamReader
            ReaderToDispose = $streamReader
            StreamToDispose = $gzipStream
            FileToDispose = $fileStream
        }
    }

    $plainReader = New-Object System.IO.StreamReader($fileStream)
    return [pscustomobject]@{
        Reader = $plainReader
        ReaderToDispose = $plainReader
        StreamToDispose = $null
        FileToDispose = $fileStream
    }
}

$createBlocks = [System.Collections.Generic.List[string]]::new()
$identityBlocks = [System.Collections.Generic.List[string]]::new()
$constraintBlocks = [System.Collections.Generic.List[string]]::new()
$copyBlocks = [System.Collections.Generic.List[string]]::new()

$readerHolder = New-Reader -Path $DumpPath
$reader = $readerHolder.Reader

try {
    while (($line = $reader.ReadLine()) -ne $null) {
        if ($line -match '^CREATE TABLE (public\."[^"]+") \($') {
            $tableName = $matches[1]
            $block = [System.Collections.Generic.List[string]]::new()
            $block.Add($line)

            while (($nextLine = $reader.ReadLine()) -ne $null) {
                $block.Add($nextLine)
                if ($nextLine -eq ');') {
                    break
                }
            }

            if ($allowedTables -contains $tableName) {
                foreach ($blockLine in $block) {
                    $createBlocks.Add($blockLine)
                }
                $createBlocks.Add("")
            }

            continue
        }

        if ($line -match '^ALTER TABLE public\."QuestionsAnswers" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY \($') {
            $block = [System.Collections.Generic.List[string]]::new()
            $block.Add($line)

            while (($nextLine = $reader.ReadLine()) -ne $null) {
                $block.Add($nextLine)
                if ($nextLine -eq ');') {
                    break
                }
            }

            foreach ($blockLine in $block) {
                $identityBlocks.Add($blockLine)
            }
            $identityBlocks.Add("")
            continue
        }

        if ($line -match '^ALTER TABLE ONLY (public\."[^"]+")$') {
            $tableName = $matches[1]
            $nextLine = $reader.ReadLine()
            if ($null -eq $nextLine) {
                break
            }

            if (($allowedTables -contains $tableName) -and $nextLine -match 'ADD CONSTRAINT') {
                $constraintBlocks.Add($line)
                $constraintBlocks.Add($nextLine)
                $constraintBlocks.Add("")
            }

            continue
        }

        if ($line -match '^COPY (public\."[^"]+") ') {
            $tableName = $matches[1]
            $block = [System.Collections.Generic.List[string]]::new()
            $block.Add($line)

            while (($nextLine = $reader.ReadLine()) -ne $null) {
                $block.Add($nextLine)
                if ($nextLine -eq '\.') {
                    break
                }
            }

            if ($allowedTables -contains $tableName) {
                foreach ($blockLine in $block) {
                    $copyBlocks.Add($blockLine)
                }
                $copyBlocks.Add("")
            }

            continue
        }
    }
}
finally {
    if ($readerHolder.ReaderToDispose) { $readerHolder.ReaderToDispose.Dispose() }
    if ($readerHolder.StreamToDispose) { $readerHolder.StreamToDispose.Dispose() }
    if ($readerHolder.FileToDispose) { $readerHolder.FileToDispose.Dispose() }
}

$output = [System.Collections.Generic.List[string]]::new()
$output.Add("-- Generated from legacy Supabase cluster dump")
$output.Add("-- Keeps only the app-owned public tables.")
$output.Add("BEGIN;")
$output.Add("")
foreach ($drop in $tableDrops) {
    $output.Add($drop)
}
$output.Add("")
foreach ($line in $createBlocks) { $output.Add($line) }
foreach ($line in $identityBlocks) { $output.Add($line) }
foreach ($line in $constraintBlocks) { $output.Add($line) }
foreach ($line in $copyBlocks) { $output.Add($line) }
$output.Add("COMMIT;")
$output.Add("")

[System.IO.File]::WriteAllLines($OutputPath, $output)
Write-Host "Wrote sanitized restore SQL to $OutputPath"
