begin;

alter table if exists public."QuestionsAnswers"
    add column if not exists "secondarySum" integer not null default -1111;

alter table if exists public."QuestionsAnswers"
    add column if not exists "secondaryAddend1" integer not null default -1111;

alter table if exists public."QuestionsAnswers"
    add column if not exists "secondaryAddend2" integer not null default -1111;

alter table if exists public."QuestionsAnswers"
    add column if not exists "secondarySumEnabled" boolean not null default false;

alter table if exists public."QuestionsAnswers"
    add column if not exists "secondaryAddend1Enabled" boolean not null default false;

alter table if exists public."QuestionsAnswers"
    add column if not exists "secondaryAddend2Enabled" boolean not null default false;

create table if not exists public."KeyboardQuestion"
(
    "QuestionID" bigint generated by default as identity primary key,
    "QuestionNumber" integer not null,
    "AttemptNumber" integer not null default 0,
    "GameId" text not null,
    "Time" timestamptz not null default now(),
    "UserId" uuid not null default '00000000-0000-0000-0000-000000000000',
    "ResultStatus" integer not null default 0,
    "WasTutorialUsed" boolean not null default false,
    "aboveNumber" integer null,
    "length" integer null,
    "MoveByLength" integer null,
    "KeyboardRows" integer not null default 1,
    "KeyboardKeysInRow" integer not null default 10,
    "ShowNumbersOnKeys" boolean not null default false,
    "QuestionPromptText" text null,
    "ConfigJson" text null,
    "ConfigJson2" text null,
    "ConfigJson3" text null,
    "ConfigJson4" text null,
    "SubmittedKeyboardJson" text null,
    "KeyboardWeightsJson" text null,
    "InitialKeyboardStateJson" text null,
    "MoveByDirectionJson" text null,
    "SubmittedTime" timestamptz null
);

create index if not exists "IX_KeyboardQuestion_GameId_QuestionNumber_AttemptNumber"
    on public."KeyboardQuestion" ("GameId", "QuestionNumber", "AttemptNumber");

create table if not exists public."KeyEvent"
(
    "id" bigint generated by default as identity primary key,
    "GameId" text not null,
    "QuestionNumber" integer not null,
    "AttemptNumber" integer not null default 0,
    "EventType" integer not null,
    "KeyNumber" integer not null,
    "Row" integer not null default 0,
    "EventTime" timestamptz not null default now(),
    "RelativeX" double precision null,
    "RelativeY" double precision null
);

create index if not exists "IX_KeyEvent_GameId_QuestionNumber_AttemptNumber_EventTime"
    on public."KeyEvent" ("GameId", "QuestionNumber", "AttemptNumber", "EventTime");

create table if not exists public."TimerChangeEvent"
(
    "Id" bigint generated by default as identity primary key,
    "GameId" text not null,
    "QuestionNumber" integer not null,
    "EventTime" timestamptz not null default now(),
    "OldSetting" integer not null,
    "NewSetting" integer not null,
    "Source" text not null default ''
);

create index if not exists "IX_TimerChangeEvent_GameId_QuestionNumber_EventTime"
    on public."TimerChangeEvent" ("GameId", "QuestionNumber", "EventTime");

create table if not exists public."VisibilityChangeEvent"
(
    "Id" bigint generated by default as identity primary key,
    "GameId" text not null,
    "QuestionNumber" integer not null,
    "EventTime" timestamptz not null default now(),
    "Target" text not null default '',
    "WasVisible" boolean not null default false,
    "IsVisible" boolean not null default false,
    "WasInitiallyVisible" boolean not null default false,
    "Source" text not null default ''
);

create index if not exists "IX_VisibilityChangeEvent_GameId_QuestionNumber_EventTime"
    on public."VisibilityChangeEvent" ("GameId", "QuestionNumber", "EventTime");

create table if not exists public."QuestionAnswerPart"
(
    "Id" bigint generated by default as identity primary key,
    "GameId" text not null,
    "QuestionNumber" integer not null,
    "RowIndex" integer not null,
    "ColumnIndex" integer not null,
    "ValueText" text not null default '',
    "IsEnabled" boolean not null default true
);

create index if not exists "IX_QuestionAnswerPart_GameId_QuestionNumber_RowIndex_ColumnIndex"
    on public."QuestionAnswerPart" ("GameId", "QuestionNumber", "RowIndex", "ColumnIndex");

commit;
